name: Terraform CI

on:
  pull_request:
    branches:
      - main  # Change this if your main branch is named differently

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
     run:
      working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.9.7  # Specify the minimum version you want to use

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive
        
      - name: Terraform Validate
        run: terraform validate
        
